### ISSUE TITLE
Improve build automation

### ISSUE THREAD

**Issue by mgrosperrin** [mgrosperrin/commandlineparser#13]
The build script should run the tests, create a package and upload it to nuget.org or myget.org galleries.
The AppVeyor build should be updated to build and publish the dev branch to myget.org, the master branch to nuget.org and just build the others branches.

**Comment by ArsenShnurkov** [comment]
There should be no such thing as "build script for cmd". PowerShell (windows) and pash (linux)  are actual now.

If you don't want to write powershell script, then please use .proj files for msbuild. They can be build from linux with xbuild utility. And .cmd files can't

**Comment by mgrosperrin** [comment]
Hi,
I'm currently working on it and implementing it as MSBuild scripts. The scripts will mainly be here to produce the Nuget package.
I'm pretty sure the scripts will not be compatible with non-Windows platforms on the first version (I have to call `nuget.exe`).
The compatibility with Mono and non-Windows platforms is not my top priority at this time even if I will try to not be incompatible.
