### ISSUE TITLE
Installation instruction fails

### ISSUE THREAD

**Issue by ArsenShnurkov** [mgrosperrin/commandlineparser#14]
<pre>sabayon ~ # pash
Pash - Copyright (C) Pash Contributors. License: GPL/BSD. See https://github.com/Pash-Project/Pash/

PASH /home/user> Install-Package MGR.CommandLineParser
Command 'Install-Package' not found.
  +CategoryInfo: ObjectNotFound, Reason: ParentContainsErrorRecordException
  +FullyQualifiedErrorId: CommandNotFoundException
PASH /home/user></pre>

**Comment by mgrosperrin** [comment]
Hi,

this command is a powershell command that have to be run in the package manager console in Visual Studio.
I will update the docs in order to precise it.

**Comment by ArsenShnurkov** [comment]
an article about addin for monodevelop:
http://lastexitcode.com/blog/2014/06/22/NuGetPowerShellConsoleForXamarinStudio/

**Comment by mgrosperrin** [comment]
I don't know Monodevelop but the article suggests that the command should works in the package console extension.
